/**
 * SQL das rotas LH — replica fiel da query de produção do generate_map.py
 * Inclui: checkpoints, GPS, LF, FOS, DIT, Prio, Costs, vehicle capacity
 * ETA_DATE é o campo chave para o filtro de data da aba E2E
 */
export const BQ_QUERY_LH_ROUTES = (dateFrom: string, dateTo: string): string => `
WITH
ROUTES AS (
  SELECT
    SHP_LG_ROUTE_ID
  , SHP_LG_ROUTE_CODE
  , SIT_SITE_ID
  , SHP_ROUTE_TYPE
  , SHP_LG_ROUTE_STATUS
  , SHP_LG_CARRIER_NAME
  , SHP_LG_VEHICLE_TYPE
  , COALESCE(SHP_LG_VEHICLE_TYPE_PLANNED,
      MAX(SHP_LG_VEHICLE_TYPE_PLANNED) OVER (PARTITION BY SHP_LG_ROUTE_ID)
    )                                                                        AS SHP_LG_VEHICLE_TYPE_PLANNED
  , COALESCE(SHP_LG_FIRST_PLATE, SHP_LG_VEHICLE_LICENSE_PLATE)  AS PLATE_TRACTOR
  , SHP_LG_SECOND_PLATE                                          AS PLATE_TRAILER_1
  , SHP_LG_THIRD_PLATE                                           AS PLATE_TRAILER_2
  , SHP_LG_DRIVER_ID
  , SHP_BILLING_TYPE
  , SHP_ORDER_TYPE
  , SHP_ROUTE_INIT_DATE_DTTM
  , CAST(SHP_ROUTE_INIT_DATE_DTTM AS DATE)                       AS ROUTE_DATE
  , DATE(SHP_DESTINATION_ETA_DTTM)                               AS ETA_DATE
  -- Checkpoints Origem
  , CAST(SHP_LG_ORIGIN_PRE_ARRIVAL_DATE      AS DATETIME)        AS ORIGIN_PRE_CHECK_DTTM
  , CAST(SHP_LG_DESTINATION_PRE_ARRIVAL_DATE AS DATETIME)        AS DEST_PRE_CHECK_DTTM
  , SHP_ORIGIN_ETA_DTTM
  , SHP_ORIGIN_ATA_DTTM
  , SHP_ORIGIN_ATA_SOURCE
  , SHP_ORIGIN_DOCK_IN_DTTM
  , SHP_ORIGIN_ETD_DTTM
  , SHP_ORIGIN_ATD_DTTM
  , SHP_ORIGIN_ETD_SOURCE
  , SHP_ORIGIN_DOCK_OUT_DTTM
  -- Checkpoints Destino
  , SHP_DESTINATION_ETA_DTTM
  , SHP_DESTINATION_ATA_DTTM
  , SHP_DESTINATION_ATA_SOURCE
  , SHP_DESTINATION_DOCK_IN_DTTM
  , SHP_DESTINATION_ETD_DTTM
  , SHP_DESTINATION_ATD_DTTM
  , SHP_DESTINATION_ATD_SOURCE
  , SHP_DESTINATION_DOCK_OUT_DTTM
  -- Load Factor
  , SHP_TOTAL_PALLET_POSITIONS_LF_AMT
  , SHP_OCCUPIED_PALLET_POSITIONS_LF_AMT
  , ROUND(SHP_PALLETIZABLE_LOAD_FACTOR_PERC, 1)                  AS LF_PALLET_PERC
  , ROUND(SHP_WATERFILL_LOAD_FACTOR_PERC,   1)                  AS LF_VOLUME_PERC
  , ROUND(SHP_AVG_SHIPMENTS_PER_PALLET_LF,  1)                  AS AVG_SHP_PER_PAL
  , SHP_ORIGIN_FACILITY_ID
  , SHP_ORIGIN_REGIONAL_L1
  , SHP_DESTINATION_FACILITY_ID
  , SHP_DESTINATION_REGIONAL_L1
  , CAST(SHP_ORIGIN_LATITUDE      AS FLOAT64)                    AS ORIGIN_LAT
  , CAST(SHP_ORIGIN_LONGITUDE     AS FLOAT64)                    AS ORIGIN_LNG
  , CAST(SHP_DESTINATION_LATITUDE AS FLOAT64)                    AS DEST_LAT
  , CAST(SHP_DESTINATION_LONGITUDE AS FLOAT64)                   AS DEST_LNG
  , DISTANCE_KM
  , DATETIME_DIFF(SHP_DESTINATION_ATA_DTTM, SHP_DESTINATION_ETA_DTTM, MINUTE) AS DELAY_MINUTES
  , CASE
      WHEN SHP_DESTINATION_ATA_DTTM IS NULL                                                   THEN 'SEM_ATA'
      WHEN DATETIME_DIFF(SHP_DESTINATION_ATA_DTTM, SHP_DESTINATION_ETA_DTTM, MINUTE) <= 0    THEN 'ON_TIME'
      WHEN DATETIME_DIFF(SHP_DESTINATION_ATA_DTTM, SHP_DESTINATION_ETA_DTTM, MINUTE) <= 60   THEN 'DELAY_ATE_1H'
      WHEN DATETIME_DIFF(SHP_DESTINATION_ATA_DTTM, SHP_DESTINATION_ETA_DTTM, MINUTE) <= 180  THEN 'DELAY_1H_3H'
      WHEN DATETIME_DIFF(SHP_DESTINATION_ATA_DTTM, SHP_DESTINATION_ETA_DTTM, MINUTE) <= 360  THEN 'DELAY_3H_6H'
      ELSE                                                                                      'DELAY_6H_PLUS'
    END                                                                          AS DELAY_BUCKET
  , SHP_TOTAL_PACKAGES_PICKUP_AMT
  , SHP_TOTAL_PACKAGES_DROPOFF_AMT
  , SHP_COUNT_LOCATIONS_MELI_DRIVER_AMT
  , SHP_COUNT_LOCATIONS_BRK_AMT
  , SHP_LAST_DATE_LOCATION_MELI_DRIVER_DTTM
  , SHP_LAST_DATE_LOCATION_BRK_DTTM
  , SHP_MMRTT_EXPECTED_ARRIVAL_DATE_DTTM
  , SHP_MMRTT_ESTIMATION_ADDITIONAL_FIELDS
  , SHP_MMRTT_COMPUTED_DATE_DTTM
  , SHP_MMRTT_ESTIMATION_SOURCE
  , SHP_TYPE_INCIDENT_DESTINATION_ETA_DESCRIPTION                AS INCIDENT_TYPE
  , SHP_DELAY_FORECAST_INCIDENT_MINUTES
  , ROW_NUMBER() OVER (
      PARTITION BY SHP_LG_ROUTE_ID
      ORDER BY
        CASE WHEN SHP_ORIGIN_ATD_DTTM IS NOT NULL AND SHP_DESTINATION_ATA_DTTM IS NULL THEN 0 ELSE 1 END,
        SHP_ORIGIN_ATD_DTTM DESC NULLS LAST,
        SHP_DESTINATION_ETA_DTTM DESC NULLS LAST
    ) AS leg_rn
  , MAX(COALESCE(AUD_UPD_DTTM, AUD_INS_DTTM)) OVER () AS TABLE_LAST_UPD
  FROM \`meli-bi-data.WHOWNER.BT_SHP_OC_LH_ROUTES\`
  WHERE
    DATE(SHP_DESTINATION_ETA_DTTM) BETWEEN '${dateFrom}' AND '${dateTo}'
    AND SHP_ORIGIN_LATITUDE IS NOT NULL AND SHP_ORIGIN_LATITUDE != 0
    AND SHP_DESTINATION_LATITUDE IS NOT NULL AND SHP_DESTINATION_LATITUDE != 0
    AND SIT_SITE_ID = 'MLB'
    AND SHP_ROUTE_TYPE = 'LINE HAUL'
),
-- Capacidade nominal do tipo de veículo
VEHICLE_CAP AS (
  SELECT DISTINCT
    UPPER(SHP_LG_VEHICLE_TYPE) AS VEHICLE_TYPE
  , SHP_LG_VEHICLE_CAPACITY    AS CAP_M3
  , SHP_LG_VEHICLE_WEIGHT      AS CAP_KG
  FROM \`meli-bi-data.WHOWNER.LK_SHP_LG_VEHICLES_TYPES\`
  WHERE SIT_SITE_ID = 'MLB'
),
-- Capacidade de paletes por tipo de veículo (derivada das rotas recentes)
VEH_PAL_CAP AS (
  SELECT
    UPPER(SHP_LG_VEHICLE_TYPE)             AS VEHICLE_TYPE
  , MAX(SHP_TOTAL_PALLET_POSITIONS_LF_AMT) AS CAP_PAL
  FROM \`meli-bi-data.WHOWNER.BT_SHP_OC_LH_ROUTES\`
  WHERE SIT_SITE_ID = 'MLB'
    AND SHP_ROUTE_TYPE = 'LINE HAUL'
    AND SHP_TOTAL_PALLET_POSITIONS_LF_AMT > 0
    AND DATE(SHP_DESTINATION_ETA_DTTM) >= DATE_SUB(CURRENT_DATE('America/Sao_Paulo'), INTERVAL 3 DAY)
  GROUP BY 1
),
-- Shipments da rota (bridge table para FOS, DIT e Prio)
SHIPMENTS AS (
  SELECT M.ROUTE_ID, M.SHP_SHIPMENT_ID, M.HU_ID
  FROM \`meli-bi-data.WHOWNER.LK_SHP_TRACKER_MONITORING_LH\` M
  WHERE M.ROUTE_ID IN (SELECT SHP_LG_ROUTE_ID FROM ROUTES WHERE leg_rn = 1)
),
-- FOS Inbound: recebimento físico do HU no hub destino
FOS_RAW AS (
  SELECT
    F.CONTAINER.CONTENT_CODE                 AS HU_ID
  , CAST(F.TRANSFER.FINISH_DATE AS DATETIME) AS FOS_FINISH_DATE
  FROM \`meli-bi-data.WHOWNER.BT_SHP_MT_MONITOREO_ASSERTIVENESS\` F
  WHERE F.SITE_ID = 'MLB'
    AND F.CONTAINER.CONTENT_CODE IN (SELECT HU_ID FROM SHIPMENTS WHERE HU_ID IS NOT NULL)
),
FOS_DEDUP AS (
  SELECT HU_ID, MAX(FOS_FINISH_DATE) AS FOS_FINISH_DATE
  FROM FOS_RAW GROUP BY HU_ID
),
FOS_AGG AS (
  SELECT
    S.ROUTE_ID
  , COUNTIF(FD.FOS_FINISH_DATE IS NOT NULL)         AS FOS_SIM_COUNT
  , COUNT(S.HU_ID)                                  AS FOS_TOTAL_COUNT
  , DATETIME_TRUNC(MIN(FD.FOS_FINISH_DATE), SECOND) AS FOS_FINISH_DTTM
  FROM SHIPMENTS S
  LEFT JOIN FOS_DEDUP FD ON S.HU_ID = FD.HU_ID
  GROUP BY S.ROUTE_ID
),
-- Priority class por rota
PRIO_AGG AS (
  SELECT
    S.ROUTE_ID
  , COUNT(SHP.SHP_SHIPMENT_ID)                                            AS PRIO_TOTAL
  , COUNTIF(SHP.SHP_PRIORITY_CLASS IN ('10','20','25'))                   AS PRIO_FAST
  , COUNTIF(SHP.SHP_PRIORITY_CLASS = '30')                                AS PRIO_STANDARD
  , COUNTIF(SHP.SHP_PRIORITY_CLASS = '50')                                AS PRIO_SLOW
  , COUNTIF(SHP.SHP_PRIORITY_CLASS = '60')                                AS PRIO_CHEAPEST
  , COUNTIF(SHP.SHP_PRIORITY_CLASS NOT IN ('10','20','25','30','50','60')
         OR SHP.SHP_SHIPMENT_ID IS NULL)                                  AS PRIO_OTHER
  FROM SHIPMENTS S
  LEFT JOIN \`meli-bi-data.WHOWNER.BT_SHP_SHIPMENTS\` SHP
    ON CAST(S.SHP_SHIPMENT_ID AS INT64) = SHP.SHP_SHIPMENT_ID
   AND SHP.SHP_DATE_SHIPPED_ID >= DATE_SUB(CURRENT_DATE('America/Sao_Paulo'), INTERVAL 14 DAY)
  GROUP BY S.ROUTE_ID
),
-- Cost metrics por rota
LHC_DEDUP AS (
  SELECT
    CAST(SHP_SHIPMENT_ID AS INT64) AS SHP_SHIPMENT_ID
  , CPS, CPHU, COST_GROUND, QTY_SHP_BY_ROUTE, OCCUPATION_BY_ROUTE
  , ROW_NUMBER() OVER (PARTITION BY SHP_SHIPMENT_ID ORDER BY DATE_HANDLING DESC) AS RN
  FROM \`meli-bi-data.WHOWNER.BT_SHP_LINE_HAUL_COSTS\`
  WHERE SIT_SITE_ID = 'MLB'
    AND DATE_SHIPPED >= DATE_SUB(CURRENT_DATE('America/Sao_Paulo'), INTERVAL 14 DAY)
),
COST_AGG AS (
  SELECT
    S.ROUTE_ID
  , AVG(C.CPS)                AS COST_CPS
  , AVG(C.CPHU)               AS COST_CPHU
  , MAX(C.COST_GROUND)        AS COST_GROUND
  , MAX(C.QTY_SHP_BY_ROUTE)   AS COST_QTY_SHP
  , MAX(C.OCCUPATION_BY_ROUTE) AS COST_OCCUPATION
  FROM SHIPMENTS S
  LEFT JOIN LHC_DEDUP C ON C.SHP_SHIPMENT_ID = S.SHP_SHIPMENT_ID AND C.RN = 1
  GROUP BY S.ROUTE_ID
),
-- DIT: pacotes com atraso
DIT_AGG AS (
  SELECT
    S.ROUTE_ID
  , COUNT(D.SHP_SHIPMENT_ID)                          AS DIT_COUNT
  , COUNTIF(D.LT_DELAY_CAUSE_L2 = 'Line Haul')       AS DIT_LH_COUNT
  , STRING_AGG(DISTINCT D.LT_DELAY_CAUSE_L0 LIMIT 5) AS DIT_CAUSES
  , MIN(CAST(D.SHP_PROMISE_DIT_DATE AS DATETIME))     AS DIT_PROMISE_DTTM
  , TO_JSON_STRING(ARRAY_AGG(STRUCT(
      CAST(D.SHP_SHIPMENT_ID AS STRING) AS shp
    , D.LT_DELAY_CAUSE_L0              AS cause
    , D.LT_DELAY_CAUSE_L2              AS cause_l2
    ) LIMIT 200))                                      AS DIT_DETAIL
  FROM SHIPMENTS S
  JOIN \`meli-bi-data.WHOWNER.BT_SHP_TRACKER_DELAY_CAUSE_DIT\` D
    ON D.SHP_SHIPMENT_ID = S.SHP_SHIPMENT_ID
   AND D.SHP_LEAD_TIME_DEVIATION_TYPE = 'DIT'
  GROUP BY S.ROUTE_ID
)
SELECT
  R.SHP_LG_ROUTE_ID, R.SHP_LG_ROUTE_CODE, R.SIT_SITE_ID, R.ROUTE_DATE, R.ETA_DATE, R.SHP_ROUTE_INIT_DATE_DTTM
, R.SHP_ORIGIN_FACILITY_ID, R.SHP_ORIGIN_REGIONAL_L1, R.ORIGIN_LAT, R.ORIGIN_LNG
, R.SHP_DESTINATION_FACILITY_ID, R.SHP_DESTINATION_REGIONAL_L1, R.DEST_LAT, R.DEST_LNG
, R.DISTANCE_KM
, R.SHP_LG_ROUTE_STATUS, R.DELAY_BUCKET, R.DELAY_MINUTES
, R.ORIGIN_PRE_CHECK_DTTM, R.DEST_PRE_CHECK_DTTM, R.SHP_ORIGIN_ETA_DTTM
, R.SHP_ORIGIN_ATA_DTTM, R.SHP_ORIGIN_ATA_SOURCE, R.SHP_ORIGIN_DOCK_IN_DTTM
, R.SHP_ORIGIN_ETD_DTTM, R.SHP_ORIGIN_ATD_DTTM, R.SHP_ORIGIN_ETD_SOURCE, R.SHP_ORIGIN_DOCK_OUT_DTTM
, R.SHP_DESTINATION_ETA_DTTM, R.SHP_DESTINATION_ATA_DTTM, R.SHP_DESTINATION_ATA_SOURCE, R.SHP_DESTINATION_DOCK_IN_DTTM
, R.SHP_DESTINATION_ETD_DTTM, R.SHP_DESTINATION_ATD_DTTM, R.SHP_DESTINATION_ATD_SOURCE, R.SHP_DESTINATION_DOCK_OUT_DTTM
, R.SHP_TOTAL_PALLET_POSITIONS_LF_AMT, R.SHP_OCCUPIED_PALLET_POSITIONS_LF_AMT
, R.LF_PALLET_PERC, R.LF_VOLUME_PERC, R.AVG_SHP_PER_PAL
, R.SHP_LG_CARRIER_NAME, R.SHP_LG_VEHICLE_TYPE, R.SHP_LG_VEHICLE_TYPE_PLANNED
, VPC.CAP_PAL AS VEH_PLANNED_CAP_PAL
, VCA.CAP_PAL AS VEH_ACTUAL_CAP_PAL
, R.PLATE_TRACTOR, R.PLATE_TRAILER_1, R.PLATE_TRAILER_2
, R.SHP_LG_DRIVER_ID, R.SHP_BILLING_TYPE, R.SHP_ORDER_TYPE
, R.SHP_TOTAL_PACKAGES_PICKUP_AMT, R.SHP_TOTAL_PACKAGES_DROPOFF_AMT
-- GPS
, CASE
    WHEN R.SHP_COUNT_LOCATIONS_MELI_DRIVER_AMT > 0 THEN 'MELI_DRIVER'
    WHEN R.SHP_COUNT_LOCATIONS_BRK_AMT > 0         THEN 'BRK_LICENSE_PLATE'
    ELSE 'SEM_GPS'
  END                                                             AS GPS_SOURCE_TYPE
, COALESCE(R.SHP_COUNT_LOCATIONS_MELI_DRIVER_AMT, 0)
  + COALESCE(R.SHP_COUNT_LOCATIONS_BRK_AMT, 0)                  AS GPS_COUNT
, R.SHP_MMRTT_COMPUTED_DATE_DTTM                                 AS GPS_LAST_DTTM
, DATETIME_DIFF(CURRENT_DATETIME('America/Sao_Paulo'), R.SHP_MMRTT_COMPUTED_DATE_DTTM, MINUTE) AS GPS_MINUTES_AGO
, CASE
    WHEN R.SHP_MMRTT_COMPUTED_DATE_DTTM IS NOT NULL
      AND R.SHP_MMRTT_ESTIMATION_SOURCE = 'RTT'
      AND DATETIME_DIFF(CURRENT_DATETIME('America/Sao_Paulo'), R.SHP_MMRTT_COMPUTED_DATE_DTTM, MINUTE) < 90
    THEN TRUE ELSE FALSE
  END                                                             AS GPS_IS_ACTIVE
, COALESCE(R.SHP_LAST_DATE_LOCATION_MELI_DRIVER_DTTM, R.SHP_LAST_DATE_LOCATION_BRK_DTTM, R.SHP_MMRTT_COMPUTED_DATE_DTTM) AS LAST_KNOWN_POS_DTTM
-- Posição atual interpolada
, CASE
    WHEN R.SHP_LG_ROUTE_STATUS = 'FINISHED' THEN R.DEST_LAT
    WHEN R.SHP_LG_ROUTE_STATUS = 'IN_PROGRESS'
      AND R.SHP_ORIGIN_ATD_DTTM IS NOT NULL AND R.SHP_DESTINATION_ETA_DTTM IS NOT NULL
      AND DATETIME_DIFF(R.SHP_DESTINATION_ETA_DTTM, R.SHP_ORIGIN_ATD_DTTM, MINUTE) > 0
      THEN R.ORIGIN_LAT + (R.DEST_LAT - R.ORIGIN_LAT) * LEAST(1.0, GREATEST(0.0,
             SAFE_DIVIDE(DATETIME_DIFF(CURRENT_DATETIME('America/Sao_Paulo'), R.SHP_ORIGIN_ATD_DTTM, MINUTE),
                         DATETIME_DIFF(R.SHP_DESTINATION_ETA_DTTM, R.SHP_ORIGIN_ATD_DTTM, MINUTE))))
    ELSE R.ORIGIN_LAT
  END AS CURRENT_LAT
, CASE
    WHEN R.SHP_LG_ROUTE_STATUS = 'FINISHED' THEN R.DEST_LNG
    WHEN R.SHP_LG_ROUTE_STATUS = 'IN_PROGRESS'
      AND R.SHP_ORIGIN_ATD_DTTM IS NOT NULL AND R.SHP_DESTINATION_ETA_DTTM IS NOT NULL
      AND DATETIME_DIFF(R.SHP_DESTINATION_ETA_DTTM, R.SHP_ORIGIN_ATD_DTTM, MINUTE) > 0
      THEN R.ORIGIN_LNG + (R.DEST_LNG - R.ORIGIN_LNG) * LEAST(1.0, GREATEST(0.0,
             SAFE_DIVIDE(DATETIME_DIFF(CURRENT_DATETIME('America/Sao_Paulo'), R.SHP_ORIGIN_ATD_DTTM, MINUTE),
                         DATETIME_DIFF(R.SHP_DESTINATION_ETA_DTTM, R.SHP_ORIGIN_ATD_DTTM, MINUTE))))
    ELSE R.ORIGIN_LNG
  END AS CURRENT_LNG
, CASE
    WHEN R.SHP_LG_ROUTE_STATUS = 'FINISHED' THEN 1.0
    WHEN R.SHP_LG_ROUTE_STATUS = 'IN_PROGRESS'
      AND R.SHP_ORIGIN_ATD_DTTM IS NOT NULL
      AND DATETIME_DIFF(R.SHP_DESTINATION_ETA_DTTM, R.SHP_ORIGIN_ATD_DTTM, MINUTE) > 0
      THEN ROUND(LEAST(1.0, GREATEST(0.0,
             SAFE_DIVIDE(DATETIME_DIFF(CURRENT_DATETIME('America/Sao_Paulo'), R.SHP_ORIGIN_ATD_DTTM, MINUTE),
                         DATETIME_DIFF(R.SHP_DESTINATION_ETA_DTTM, R.SHP_ORIGIN_ATD_DTTM, MINUTE)))), 3)
    ELSE 0.0
  END AS ROUTE_PROGRESS_PERC
, R.SHP_MMRTT_EXPECTED_ARRIVAL_DATE_DTTM AS ETA_RECALC_DTTM
, R.SHP_MMRTT_ESTIMATION_ADDITIONAL_FIELDS AS MMRTT_REMAINING
, R.INCIDENT_TYPE, R.SHP_DELAY_FORECAST_INCIDENT_MINUTES
, VC.CAP_M3 AS VEHICLE_CAP_M3
, VC.CAP_KG AS VEHICLE_CAP_KG
-- FOS
, COALESCE(FA.FOS_SIM_COUNT,   0) AS FOS_SIM_COUNT
, COALESCE(FA.FOS_TOTAL_COUNT, 0) AS FOS_TOTAL_COUNT
, FA.FOS_FINISH_DTTM
-- DIT
, COALESCE(DA.DIT_COUNT,    0)    AS DIT_COUNT
, COALESCE(DA.DIT_LH_COUNT, 0)    AS DIT_LH_COUNT
, DA.DIT_CAUSES
, DA.DIT_PROMISE_DTTM
, DA.DIT_DETAIL
-- Priority
, COALESCE(PA.PRIO_TOTAL,    0)   AS PRIO_TOTAL
, COALESCE(PA.PRIO_CHEAPEST, 0)   AS PRIO_CHEAPEST
, COALESCE(PA.PRIO_SLOW,     0)   AS PRIO_SLOW
, COALESCE(PA.PRIO_FAST,     0)   AS PRIO_FAST
, COALESCE(PA.PRIO_STANDARD, 0)   AS PRIO_STANDARD
, COALESCE(PA.PRIO_OTHER,    0)   AS PRIO_OTHER
-- Costs
, CA.COST_CPS
, CA.COST_CPHU
, CA.COST_GROUND
, CA.COST_QTY_SHP
, CA.COST_OCCUPATION
-- TABLE_LAST_UPD propagado para o primeiro nível
, R.TABLE_LAST_UPD
FROM ROUTES R
LEFT JOIN VEHICLE_CAP VC  ON VC.VEHICLE_TYPE = UPPER(R.SHP_LG_VEHICLE_TYPE)
LEFT JOIN VEH_PAL_CAP VPC ON VPC.VEHICLE_TYPE = UPPER(R.SHP_LG_VEHICLE_TYPE_PLANNED)
LEFT JOIN VEH_PAL_CAP VCA ON VCA.VEHICLE_TYPE = UPPER(R.SHP_LG_VEHICLE_TYPE)
LEFT JOIN FOS_AGG FA       ON FA.ROUTE_ID     = R.SHP_LG_ROUTE_ID
LEFT JOIN DIT_AGG DA       ON DA.ROUTE_ID     = R.SHP_LG_ROUTE_ID
LEFT JOIN PRIO_AGG PA      ON PA.ROUTE_ID     = R.SHP_LG_ROUTE_ID
LEFT JOIN COST_AGG CA      ON CA.ROUTE_ID     = R.SHP_LG_ROUTE_ID
WHERE R.leg_rn = 1
ORDER BY R.SHP_ROUTE_INIT_DATE_DTTM DESC
`;

/**
 * SQL de tracking GPS — pings de rotas IN_PROGRESS do intervalo selecionado
 * Atenção: query pesada (~12TB, BT_SHP_RTT_LOCATIONS sem partição). Subamostrada 1-em-5.
 */
export const BQ_QUERY_LH_TRACKING = (dateFrom?: string, dateTo?: string): string => {
  const dateFilter = (dateFrom && dateTo)
    ? `DATE(R.SHP_DESTINATION_ETA_DTTM) BETWEEN '${dateFrom}' AND '${dateTo}'`
    : `DATE(R.SHP_DESTINATION_ETA_DTTM) = CURRENT_DATE('America/Sao_Paulo')`;
  return `
WITH
BEST_DEVICE AS (
  SELECT SHP_LG_ROUTE_ID, SHP_RTT_LOCATION_DEVICE_ID, SHP_EXTERNAL_ENTITY_TYPE AS GPS_SOURCE_TYPE
  FROM (
    SELECT SHP_LG_ROUTE_ID, SHP_RTT_LOCATION_DEVICE_ID, SHP_EXTERNAL_ENTITY_TYPE,
      ROW_NUMBER() OVER (
        PARTITION BY SHP_LG_ROUTE_ID
        ORDER BY LAST_DATE_LOCATION DESC,
          CASE SHP_EXTERNAL_ENTITY_TYPE WHEN 'MELI_DRIVER' THEN 1 WHEN 'BRK_LICENSE_PLATE' THEN 2 ELSE 3 END,
          COUNT_LOCATIONS DESC
      ) AS rn
    FROM \`meli-bi-data.WHOWNER.BT_SHP_ROUTE_LOCATIONS_ADOPTION\`
    WHERE SHP_LG_TYPE = 'middle_mile'
  )
  WHERE rn = 1
),
ACTIVE_RAW AS (
  SELECT
    R.SHP_LG_ROUTE_ID, D.SHP_RTT_LOCATION_DEVICE_ID, D.GPS_SOURCE_TYPE
  , COALESCE(R.SHP_ORIGIN_ATA_DTTM, R.SHP_ORIGIN_ATD_DTTM, R.SHP_ROUTE_INIT_DATE_DTTM) AS TRACK_START_DTTM
  , R.SHP_DESTINATION_ATA_DTTM AS TRACK_END_DTTM
  , CAST(R.SHP_ORIGIN_LATITUDE      AS FLOAT64) AS ORIGIN_LAT
  , CAST(R.SHP_ORIGIN_LONGITUDE     AS FLOAT64) AS ORIGIN_LNG
  , CAST(R.SHP_DESTINATION_LATITUDE AS FLOAT64) AS DEST_LAT
  , CAST(R.SHP_DESTINATION_LONGITUDE AS FLOAT64) AS DEST_LNG
  , ROW_NUMBER() OVER (
      PARTITION BY R.SHP_LG_ROUTE_ID
      ORDER BY CASE WHEN R.SHP_ORIGIN_ATD_DTTM IS NOT NULL AND R.SHP_DESTINATION_ATA_DTTM IS NULL THEN 0 ELSE 1 END,
               R.SHP_ORIGIN_ATD_DTTM DESC NULLS LAST
    ) AS leg_rn
  FROM \`meli-bi-data.WHOWNER.BT_SHP_OC_LH_ROUTES\` R
  JOIN BEST_DEVICE D ON D.SHP_LG_ROUTE_ID = R.SHP_LG_ROUTE_ID
  WHERE ${dateFilter}
    AND R.SHP_LG_ROUTE_STATUS = 'IN_PROGRESS'
    AND R.SIT_SITE_ID = 'MLB'
    AND R.SHP_ROUTE_TYPE = 'LINE HAUL'
),
ACTIVE AS (
  SELECT SHP_LG_ROUTE_ID, SHP_RTT_LOCATION_DEVICE_ID, GPS_SOURCE_TYPE
       , TRACK_START_DTTM, TRACK_END_DTTM
       , ORIGIN_LAT, ORIGIN_LNG, DEST_LAT, DEST_LNG
  FROM ACTIVE_RAW WHERE leg_rn = 1
),
PINGS_RAW AS (
  SELECT
    A.SHP_LG_ROUTE_ID, A.GPS_SOURCE_TYPE
  , SAFE_CAST(L.SHP_RTT_LOCATION_LATITUDE  AS FLOAT64) AS LAT
  , SAFE_CAST(L.SHP_RTT_LOCATION_LONGITUDE AS FLOAT64) AS LNG
  , L.SHP_DATE_OCCURRED_DTTM AS EVENT_TS
  , ROUND(SAFE_CAST(L.SHP_RTT_LOCATION_SPEED AS FLOAT64), 1) AS SPD
  , 2*6371000*ASIN(SQRT(POW(SIN((SAFE_CAST(L.SHP_RTT_LOCATION_LATITUDE AS FLOAT64)-A.ORIGIN_LAT)/2*ACOS(-1.0)/180.0),2)+COS(A.ORIGIN_LAT*ACOS(-1.0)/180.0)*COS(SAFE_CAST(L.SHP_RTT_LOCATION_LATITUDE AS FLOAT64)*ACOS(-1.0)/180.0)*POW(SIN((SAFE_CAST(L.SHP_RTT_LOCATION_LONGITUDE AS FLOAT64)-A.ORIGIN_LNG)/2*ACOS(-1.0)/180.0),2))) AS dist_origin_m
  , 2*6371000*ASIN(SQRT(POW(SIN((SAFE_CAST(L.SHP_RTT_LOCATION_LATITUDE AS FLOAT64)-A.DEST_LAT)/2*ACOS(-1.0)/180.0),2)+COS(A.DEST_LAT*ACOS(-1.0)/180.0)*COS(SAFE_CAST(L.SHP_RTT_LOCATION_LATITUDE AS FLOAT64)*ACOS(-1.0)/180.0)*POW(SIN((SAFE_CAST(L.SHP_RTT_LOCATION_LONGITUDE AS FLOAT64)-A.DEST_LNG)/2*ACOS(-1.0)/180.0),2))) AS dist_dest_m
  , ROW_NUMBER() OVER (PARTITION BY A.SHP_LG_ROUTE_ID ORDER BY L.SHP_DATE_OCCURRED_DTTM) AS ping_seq
  FROM ACTIVE A
  JOIN \`meli-bi-data.WHOWNER.BT_SHP_RTT_LOCATIONS\` L
    ON L.SHP_RTT_LOCATION_DEVICE_ID = A.SHP_RTT_LOCATION_DEVICE_ID
   AND L.SHP_DATE_OCCURRED_DTTM >= A.TRACK_START_DTTM
   AND (A.TRACK_END_DTTM IS NULL OR L.SHP_DATE_OCCURRED_DTTM <= A.TRACK_END_DTTM)
   AND DATE(L.SHP_DATE_OCCURRED_DTTM) >= DATE_SUB(CURRENT_DATE('America/Sao_Paulo'), INTERVAL 4 DAY)
   AND SAFE_CAST(L.SHP_RTT_LOCATION_LATITUDE  AS FLOAT64) BETWEEN -35 AND 6
   AND SAFE_CAST(L.SHP_RTT_LOCATION_LONGITUDE AS FLOAT64) BETWEEN -74 AND -34
),
GEO_BOUNDS AS (
  SELECT SHP_LG_ROUTE_ID
  , MIN(CASE WHEN dist_origin_m <= 50000 THEN ping_seq END) AS first_near_origin_seq
  , MIN(CASE WHEN dist_dest_m   <= 30000 THEN ping_seq END) AS first_near_dest_seq
  FROM PINGS_RAW GROUP BY SHP_LG_ROUTE_ID
),
PINGS_WITH_PREV AS (
  SELECT P.*
  , LAG(P.LAT)      OVER (PARTITION BY P.SHP_LG_ROUTE_ID ORDER BY P.EVENT_TS) AS prev_lat
  , LAG(P.LNG)      OVER (PARTITION BY P.SHP_LG_ROUTE_ID ORDER BY P.EVENT_TS) AS prev_lng
  , LAG(P.EVENT_TS) OVER (PARTITION BY P.SHP_LG_ROUTE_ID ORDER BY P.EVENT_TS) AS prev_ts
  , LAG(P.dist_dest_m) OVER (PARTITION BY P.SHP_LG_ROUTE_ID ORDER BY P.EVENT_TS) AS prev_dist_dest_m
  FROM PINGS_RAW P
  JOIN GEO_BOUNDS G ON G.SHP_LG_ROUTE_ID = P.SHP_LG_ROUTE_ID
  WHERE P.ping_seq >= COALESCE(G.first_near_origin_seq, 1)
    AND (G.first_near_dest_seq IS NULL OR P.ping_seq < G.first_near_dest_seq)
),
PINGS_FLAGGED AS (
  SELECT *
  , TIMESTAMP_DIFF(EVENT_TS, prev_ts, SECOND) AS dt_sec
  , 2*6371000*ASIN(SQRT(POW(SIN((LAT-prev_lat)/2*ACOS(-1.0)/180.0),2)+COS(prev_lat*ACOS(-1.0)/180.0)*COS(LAT*ACOS(-1.0)/180.0)*POW(SIN((LNG-prev_lng)/2*ACOS(-1.0)/180.0),2))) AS dist_m
  FROM PINGS_WITH_PREV
),
PINGS_NUMBERED AS (
  SELECT *
  , SAFE_DIVIDE(dist_m, dt_sec) * 3.6 AS v_kmh
  , CASE
      WHEN prev_ts IS NULL THEN 0
      WHEN dt_sec <= 0 THEN 1
      WHEN SAFE_DIVIDE(dist_m, dt_sec)*3.6 > 160 THEN 1
      WHEN SAFE_DIVIDE(dist_m, dt_sec)*3.6 < 3 AND dist_dest_m - COALESCE(prev_dist_dest_m, dist_dest_m) > 8000 THEN 1
      ELSE 0
    END AS is_outlier
  FROM PINGS_FLAGGED
),
PINGS_SEG AS (
  SELECT *
  , 1 + SUM(is_outlier) OVER (PARTITION BY SHP_LG_ROUTE_ID ORDER BY EVENT_TS ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS segment_id
  FROM PINGS_NUMBERED
)
SELECT
  SHP_LG_ROUTE_ID
, LAT, LNG
, FORMAT_DATETIME('%H:%M', EVENT_TS) AS TS_HM
, SPD
, segment_id AS SEG
FROM PINGS_SEG
WHERE is_outlier = 0
  AND (MOD(ping_seq, 5) = 0 OR ping_seq = 1)
ORDER BY SHP_LG_ROUTE_ID, EVENT_TS
`;
};
