export function BQ_QUERY_DIT_ROUTES(dateFrom: string, dateTo: string): string {
  return `
WITH
ROUTES_RAW AS (
  SELECT
    SHP_LG_ROUTE_ID
  , SHP_LG_ROUTE_CODE
  , SHP_LG_ROUTE_STATUS
  , SHP_LG_CARRIER_NAME
  , SHP_ROUTE_TYPE
  , SHP_ORIGIN_FACILITY_ID
  , SHP_ORIGIN_REGIONAL_L1
  , SHP_DESTINATION_FACILITY_ID
  , SHP_DESTINATION_REGIONAL_L1
  , DATE(SHP_DESTINATION_ETA_DTTM)                                                AS ETA_DATE
  , SHP_ORIGIN_ETD_DTTM
  , SHP_ORIGIN_ATD_DTTM
  , SHP_DESTINATION_ETA_DTTM
  , SHP_DESTINATION_ATA_DTTM
  , DATETIME_DIFF(SHP_DESTINATION_ATA_DTTM, SHP_DESTINATION_ETA_DTTM, MINUTE)    AS DELAY_MINUTES
  , DATETIME_DIFF(SHP_ORIGIN_ATD_DTTM, SHP_ORIGIN_ETD_DTTM, MINUTE)             AS GATE_OUT_DELAY_MIN
  , ROW_NUMBER() OVER (
      PARTITION BY SHP_LG_ROUTE_ID
      ORDER BY SHP_DESTINATION_ETA_DTTM DESC
    ) AS RN
  FROM \`meli-bi-data.WHOWNER.BT_SHP_OC_LH_ROUTES\`
  WHERE DATE(SHP_DESTINATION_ETA_DTTM) BETWEEN '${dateFrom}' AND '${dateTo}'
    AND SIT_SITE_ID = 'MLB'
    AND SHP_ROUTE_TYPE = 'LINE HAUL'
    AND SHP_LG_ROUTE_STATUS NOT IN ('CANCELLED','CANCELED')
),
ROUTES AS (
  SELECT * EXCEPT(RN) FROM ROUTES_RAW WHERE RN = 1
),
SHIPMENTS AS (
  SELECT ROUTE_ID, SHP_SHIPMENT_ID
  FROM \`meli-bi-data.WHOWNER.LK_SHP_TRACKER_MONITORING_LH\`
  WHERE ROUTE_ID IN (SELECT SHP_LG_ROUTE_ID FROM ROUTES)
),
DIT AS (
  SELECT D.SHP_SHIPMENT_ID, D.LT_DELAY_CAUSE_L2, D.LT_DELAY_CAUSE_L1
  FROM \`meli-bi-data.WHOWNER.BT_SHP_TRACKER_DELAY_CAUSE_DIT\` D
  WHERE D.SHP_LEAD_TIME_DEVIATION_TYPE = 'DIT'
    AND D.SHP_SHIPMENT_ID IN (SELECT SHP_SHIPMENT_ID FROM SHIPMENTS)
),
ROUTE_AGG AS (
  SELECT
    S.ROUTE_ID
  , COUNT(DISTINCT S.SHP_SHIPMENT_ID)                                               AS TOTAL_SHIPMENTS
  , COUNT(DISTINCT CASE WHEN D.LT_DELAY_CAUSE_L2 = 'Line Haul'
                        THEN D.SHP_SHIPMENT_ID END)                                 AS DIT_LH_REGIONAL
  , COUNT(DISTINCT CASE WHEN D.LT_DELAY_CAUSE_L2 = 'Line Haul'
                         AND D.LT_DELAY_CAUSE_L1 = 'LH_GR'
                        THEN D.SHP_SHIPMENT_ID END)                                 AS DIT_LH_GR
  , COUNT(DISTINCT CASE WHEN D.LT_DELAY_CAUSE_L2 = 'Line Haul'
                         AND D.LT_DELAY_CAUSE_L1 = 'Missing LH_GR'
                        THEN D.SHP_SHIPMENT_ID END)                                 AS DIT_MISSING_LH_GR
  FROM SHIPMENTS S
  LEFT JOIN DIT D ON S.SHP_SHIPMENT_ID = D.SHP_SHIPMENT_ID
  GROUP BY ALL
)
SELECT
  R.SHP_LG_ROUTE_ID                                              AS ROUTE_ID
, R.SHP_LG_ROUTE_CODE                                           AS ROUTE_CODE
, R.SHP_LG_ROUTE_STATUS                                         AS STATUS
, R.SHP_LG_CARRIER_NAME                                         AS CARRIER
, R.SHP_ROUTE_TYPE                                              AS ROUTE_TYPE
, R.SHP_ORIGIN_REGIONAL_L1                                      AS ORIGIN_REGIONAL
, R.SHP_ORIGIN_FACILITY_ID                                      AS ORIGIN_FACILITY
, R.SHP_DESTINATION_REGIONAL_L1                                 AS DEST_REGIONAL
, R.SHP_DESTINATION_FACILITY_ID                                 AS DEST_FACILITY
, CAST(R.ETA_DATE AS STRING)                                    AS ETA_DATE
, FORMAT_DATETIME('%d/%m %H:%M', R.SHP_ORIGIN_ETD_DTTM)        AS ETD
, FORMAT_DATETIME('%d/%m %H:%M', R.SHP_ORIGIN_ATD_DTTM)        AS ATD
, FORMAT_DATETIME('%d/%m %H:%M', R.SHP_DESTINATION_ETA_DTTM)   AS ETA
, FORMAT_DATETIME('%d/%m %H:%M', R.SHP_DESTINATION_ATA_DTTM)   AS ATA
, R.DELAY_MINUTES
, R.GATE_OUT_DELAY_MIN
, COALESCE(A.TOTAL_SHIPMENTS, 0)     AS TOTAL_SHIPMENTS
, COALESCE(A.DIT_LH_REGIONAL, 0)    AS DIT_LH_REGIONAL
, COALESCE(A.DIT_LH_GR, 0)          AS DIT_LH_GR
, COALESCE(A.DIT_MISSING_LH_GR, 0)  AS DIT_MISSING_LH_GR
, ROUND(SAFE_DIVIDE(COALESCE(A.DIT_LH_REGIONAL,0),
        NULLIF(COALESCE(A.TOTAL_SHIPMENTS,0),0))*100, 2)        AS DIT_LH_PERC
FROM ROUTES R
LEFT JOIN ROUTE_AGG A ON R.SHP_LG_ROUTE_ID = A.ROUTE_ID
ORDER BY DIT_LH_REGIONAL DESC NULLS LAST
`;
}

export function BQ_QUERY_DIT_SHIPMENTS(dateFrom: string, dateTo: string): string {
  return `
WITH
ROUTES AS (
  SELECT SHP_LG_ROUTE_ID
  FROM \`meli-bi-data.WHOWNER.BT_SHP_OC_LH_ROUTES\`
  WHERE DATE(SHP_DESTINATION_ETA_DTTM) BETWEEN '${dateFrom}' AND '${dateTo}'
    AND SIT_SITE_ID = 'MLB'
    AND SHP_ROUTE_TYPE = 'LINE HAUL'
    AND SHP_LG_ROUTE_STATUS NOT IN ('CANCELLED','CANCELED')
),
SHIPMENTS AS (
  SELECT ROUTE_ID, SHP_SHIPMENT_ID, HU_ID
  FROM \`meli-bi-data.WHOWNER.LK_SHP_TRACKER_MONITORING_LH\`
  WHERE ROUTE_ID IN (SELECT SHP_LG_ROUTE_ID FROM ROUTES)
)
SELECT
  S.ROUTE_ID
, S.SHP_SHIPMENT_ID                                   AS SHIPMENT_ID
, S.HU_ID
, D.LT_DELAY_CAUSE_L1                                AS CAUSA_L1
, FORMAT_DATE('%d/%m', D.SHP_PROMISE_DIT_DATE)        AS PROMISE_DATE
FROM SHIPMENTS S
INNER JOIN \`meli-bi-data.WHOWNER.BT_SHP_TRACKER_DELAY_CAUSE_DIT\` D
  ON S.SHP_SHIPMENT_ID = D.SHP_SHIPMENT_ID
WHERE D.SHP_LEAD_TIME_DEVIATION_TYPE = 'DIT'
  AND D.LT_DELAY_CAUSE_L2 = 'Line Haul'
ORDER BY S.ROUTE_ID, D.LT_DELAY_CAUSE_L1
`;
}

export function BQ_QUERY_DIT_STEPS(dateFrom: string, dateTo: string): string {
  return `
WITH
DIT_SHPS AS (
  SELECT DISTINCT D.SHP_SHIPMENT_ID
  FROM \`meli-bi-data.WHOWNER.BT_SHP_TRACKER_DELAY_CAUSE_DIT\` D
  INNER JOIN \`meli-bi-data.WHOWNER.LK_SHP_TRACKER_MONITORING_LH\` M
    ON D.SHP_SHIPMENT_ID = M.SHP_SHIPMENT_ID
  INNER JOIN \`meli-bi-data.WHOWNER.BT_SHP_OC_LH_ROUTES\` R
    ON M.ROUTE_ID = R.SHP_LG_ROUTE_ID
  WHERE D.SHP_LEAD_TIME_DEVIATION_TYPE = 'DIT'
    AND D.LT_DELAY_CAUSE_L2 = 'Line Haul'
    AND DATE(R.SHP_DESTINATION_ETA_DTTM) BETWEEN '${dateFrom}' AND '${dateTo}'
    AND R.SIT_SITE_ID = 'MLB'
    AND R.SHP_ROUTE_TYPE = 'LINE HAUL'
    AND R.SHP_LG_ROUTE_STATUS NOT IN ('CANCELLED','CANCELED')
)
SELECT
  T.SHP_SHIPMENT_ID
, FORMAT_DATETIME('%d/%m %H:%M', T.PLAN_STEP_INITIAL_DTTM) AS PLAN_INIT
, FORMAT_DATETIME('%d/%m %H:%M', T.PLAN_STEP_FINAL_DTTM)   AS PLAN_END
, FORMAT_DATETIME('%d/%m %H:%M', T.REAL_STEP_INITIAL_DTTM) AS REAL_INIT
, FORMAT_DATETIME('%d/%m %H:%M', T.REAL_STEP_FINAL_DTTM)   AS REAL_END
, COALESCE(
    DATETIME_DIFF(T.REAL_STEP_FINAL_DTTM, T.PLAN_STEP_FINAL_DTTM, MINUTE),
    DATETIME_DIFF(T.REAL_STEP_INITIAL_DTTM, T.PLAN_STEP_INITIAL_DTTM, MINUTE)
  ) AS STEP_DELAY_MIN
, T.AUX_FINAL_DATE_SOURCE_NAME                              AS SOURCE_END
FROM \`meli-bi-data.WHOWNER.BT_SHP_TRACKER\` T
WHERE T.SHP_SHIPMENT_ID IN (SELECT SHP_SHIPMENT_ID FROM DIT_SHPS)
  AND T.PLAN_STEP_STAGE = 'LINE_HAUL'
ORDER BY T.SHP_SHIPMENT_ID
`;
}
